language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt

stages:
  - name: build
  - name: archive
    if: branch = master


jobs:
  include:
    - stage: build
      script: SLACK_TOKEN=${SLACK_TOKEN} DRY_RUN=true python slack-autoarchive.py
    - stage: archive
      script: echo 'master'
      # SLACK_TOKEN=${SLACK_TOKEN} DRY_RUN=true python slack-autoarchive.py
      